### ISSUE TITLE
About the dataset python files

### ISSUE THREAD

**Issue by panyinyin** [xdeng7/scale-aware_da#1]
I want to know the dataset code if is incomplete,like the ISPRS_dataset_multiscale_v2,DeepGlobe_crop_dataset python files I couldn't found.

**Comment by xdeng7** [comment]
Hi, they are updated. Please check.

**Comment by panyinyin** [comment]
&nbsp; &nbsp; &nbsp; &nbsp;thanks a lot！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdeng7/scale-aware_da"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 上午9:52
收件人:&nbsp;"xdeng7/scale-aware_da"<scale-aware_da@noreply.github.com&gt;;
抄送:&nbsp;"1948954467"<1948954467@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xdeng7/scale-aware_da] About the dataset python files (#1)





 
Closed #1.
